[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.16.3"
hooks = [
  {
    id = "ruff-format",
    name = "Check for formatting problems",
    types_or = ["python", "pyi"]
  },
]
